### ISSUE TITLE
Prepared statement creation doesn't return error

### ISSUE THREAD

**Issue by JTarasovic** [DATA-DOG/go-txdb#1]
This just may be something that won't work here but I thought I'd check and see.

As an example, this simple main.go

```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	_, err := sql.Open("sqlite3", "test.db")
	if err != nil {
		log.Fatal(err)
	}
}
```

and this main_test.go

```go
package main

import (
	"database/sql"
	"testing"

	"github.com/DATA-DOG/go-txdb"
	_ "github.com/mattn/go-sqlite3"
)

func init() {
	txdb.Register("txdb", "sqlite3", "test.db")
}

func TestPreparedStatement(t *testing.T) {
	db, err := sql.Open("txdb", "id")
	if err != nil {
		t.Fatal(err)
	}
	_, err = db.Prepare("THIS SHOULD FAIL...")
	if err != nil {
		t.Fatal(err)
	}
}
```

I was expecting/hoping/wishing that `TestPreparedStatement` would fail but I'm open to the possibility that either a) it's not possible or b) I'm holding it wrong. 😃

**Comment by l3pp4rd** [comment]
Hi, it does not fail because this driver does not perform any operation with database on prepare, but probably it should, in order to prevent this kind of behavior. Currently it only stores the query string to perform a Query, Exec or QueryRow later, it does not reserve a connection.

If we could prevent reserving a connection for Prepare, then it seems reasonable to call driver Prepare instead and it would work as expected. Thanks for pointing this out. I will have a look when I have time, unless you'd like to open a PR
