### ISSUE TITLE
pq: syntax error at or near "," while using txdb driver. works with plain sqlx

### ISSUE THREAD

**Issue by msonawane** [DATA-DOG/go-txdb#22]
this is sqlx.NamedExec call which has problem while running with txdb  

sql := "INSERT INTO jobs(id, url_hash, created_at, job) VALUES (:id,  :url_hash, :created_at, :job);"
_, err := s.DB.NamedExecContext(ctx, sql, jobs)

err is  pq: syntax error at or near ","

i have tried master branch as well as go mod

**Comment by l3pp4rd** [comment]
I doubt that has something to do with txdb. all txdb does is relaying everything through transaction to the actual driver.

**Comment by l3pp4rd** [comment]
Is jobs a slice? Maybe that could be the reason due to value converters?

**Comment by broothie** [comment]
I noticed this failed during named SQL commands too. I think it's somehow related to how `sqlx` binds named vars to `$1, $2, $3, ...` vs `?, ?, ?, ...` (maybe?).

I was able to workaround this by registering `txdb` as different `sqlx`-supported dollar-sign based driver, and then using that as my `sqlx` driver, e.g.:
```go
txdb.Register("pgx", "postgres", dbURL)
db, _ := sqlx.Open("pgx", "testDB")
```

This works because `sqlx` uses a fixed set of drivers to determine how to bind variables, and therefore won't recognize `"txdb"` as a driver: https://github.com/jmoiron/sqlx/blob/master/bind.go#L26

**Comment by l3pp4rd** [comment]
ah yes, that is the way to use it indeed. the same goes with other frameworks like GORM and etc..

**Comment by l3pp4rd** [comment]
maybe will need to update the readme file

**Comment by Zhenwood** [comment]
> I noticed this failed during named SQL commands too. I think it's somehow related to how `sqlx` binds named vars to `$1, $2, $3, ...` vs `?, ?, ?, ...` (maybe?).
> 
> I was able to workaround this by registering `txdb` as different `sqlx`-supported dollar-sign based driver, and then using that as my `sqlx` driver, e.g.:
> 
> ```go
> txdb.Register("pgx", "postgres", dbURL)
> db, _ := sqlx.Open("pgx", "testDB")
> ```
> 
> This works because `sqlx` uses a fixed set of drivers to determine how to bind variables, and therefore won't recognize `"txdb"` as a driver: https://github.com/jmoiron/sqlx/blob/master/bind.go#L26

You're my hero @broothie :)

**Comment by cgag** [comment]
sqlx 1.3 has a method BindDriver that lets you set the BindType to DOLLAR for txdb, or whatever driver name you want:

```
	txdb.Register("txdb", "pgx", DSN)
	sqlx.BindDriver("txdb", sqlx.DOLLAR)
```
