### ISSUE TITLE
Is it possible to run a transaction within txdb?

### ISSUE THREAD

**Issue by qdm12** [DATA-DOG/go-txdb#38]
Hello there,

I'm trying to use your driver together with the underlying mysql driver, a mysql database and [sqlx](https://github.com/jmoiron/sqlx). Unfortunately whenever I create a transaction in my production code, it fails `tx.Commit()` or `tx.Rollback()`, usually with the error saying that the save point does not exist for `tx_0` for example. Is it possible to run transactions within a (hidden) transaction started by your txdb driver?

Thanks!

**Comment by l3pp4rd** [comment]
Hi, it is possible and it uses save points for transactions. There [a test case](https://github.com/DATA-DOG/go-txdb/blob/master/db_test.go#L21) and it works well for mysql and postgres at least. If this does not work in sqlx it means it uses a different sql.DB instance opened. Are you sure that it uses the same db and not the other? Maybe you have a portion of code which opens different db instances? 

This works well for many txdb users and this is a common use case, I’m confident that it works as expected, the only reasonable issue is that you have a differnt db instancd there created and probably the code you have is not properly implemented in the first place. 

If you want any further help, produce a minimum test case example within 50 lines of code using sqlx and txdb as a tiny scenario model you have failing. Since I’m not sure what sqlx may be doing behind the scene

**Comment by qdm12** [comment]
Hello thanks for the quick reply!

Running mysql with

```sh
docker run -it --rm -p 3306:3306/tcp -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test mysql:8.0
```

With this Go code

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/DATA-DOG/go-txdb"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jmoiron/sqlx"
)

func init() {
	txdb.Register("txdb", "mysql", "root@tcp(localhost:3306)/test")
}

func main() {
	ctx := context.Background()
	os.Exit(_main(ctx))
}

func _main(ctx context.Context) int {
	db, err := sqlx.Open("txdb", "identifier")
	if err != nil {
		log.Println(err)
		return 1
	}
	defer db.Close()

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		log.Println(err)
		return 1
	}
	_, err = tx.Exec(`CREATE TABLE IF NOT EXISTS test (id INT)`)
	if err != nil {
		log.Println(err)
		return 1
	}
	err = tx.Commit()
	if err != nil {
		log.Println(err)
		return 1
	}
	return 0
}
```

Does fail with `Error 1305: SAVEPOINT tx_1 does not exist. Running it without txdb works though.

Thanks!

**Comment by qdm12** [comment]
Also I just tried replacing sqlx with database/sql and it doesn't worked either. So the issue is likely unrelated with sqlx? 🤔 Thanks for looking into this.

**Comment by l3pp4rd** [comment]
It may be the case, that begin transaction with context does is not implemented in the interface. Will have a look the next day

**Comment by l3pp4rd** [comment]
looked for some time today, there seems to be a bug in savepoint logic, made some progress, but will continue on it the another day

**Comment by qdm12** [comment]
Thanks! And amazing package by the way, I hope we can get it fixed. I also tried with `db.Begin()` without success. Let me know if I can help in any way.

**Comment by l3pp4rd** [comment]
Thanks, cannot figure this out yet, and sadly do not have that much time to spend daily. but there is certainly something not right with the Savepoints. if you have some time to contribute, it would be great if you could give a shot to determine the issue. the code part related to save points is [here](https://github.com/DATA-DOG/go-txdb/blob/master/db.go#L200-L254) the logic is to create a SAVEPOINT within transaction and store the savepoint id for rollback or commit and the error comes from the Commit part, for some reason it does not find the savepoint by the id or maybe it does not even start one, probably would be best to enable query log to see what happens there.

**Comment by l3pp4rd** [comment]
I think all the issues are related to the exec statement: 
``` go
_, err = tx.Exec(`CREATE TABLE IF NOT EXISTS test (id INT)`)
	if err != nil {
		log.Println(err)
		return 1
	}
```

Mysql does not support rolling back any table modifications. postgres on the other hand does support these in transactions.
So the mysql behavior is different when you create/alter table inside transaction. it no longer supports any savepoints or rollbacks. this is how mysql works in general. you can read about it more in [here](https://stackoverflow.com/questions/22806261/can-i-use-transactions-with-alter-table).

See here:
![2020-12-20-203415](https://user-images.githubusercontent.com/132389/102721311-a6101700-4302-11eb-84ae-a33aed12a5f5.png)

Now if we just do the usual non table modifications, it works as expexted:
![2020-12-20-203754](https://user-images.githubusercontent.com/132389/102721379-1880f700-4303-11eb-8a3b-fdfcf052fc78.png)

So txdb is working as expected and the problem is in database or the way you use it.
I personally prefer using postgres

**Comment by l3pp4rd** [comment]
I was surprised why the tests were not failing, since I had it for mysql and postgres with the savepoints, it was just that it was not mutating tables

**Comment by qdm12** [comment]
Indeed, now it works. I prefer Postgres too, MySql feels worst in many ways. But I'm stuck with it for various compatibility reasons unfortunately 😉  Anyway thanks for your time digging into this. I'm now happily using go-txdb instead of creating a database per test 🤣
